### ISSUE TITLE
sendSweetAlert no html option anymore

### ISSUE THREAD

**Issue by mayeromain** [dreamRs/shinyWidgets#48] opened 2018-01-29 11:18 UTC
I was wondering why the HTML = T option on the sendSweetAlert function has been remove? Is there a solution to use the same code as before to have some html text display in the sweet alert?
Also, is it possible not to close the alert when we click outside the popup?
Thanks

**Comment by pvictor** [comment] 2018-01-29 13:27
Hello,
This option is no longer available in sweetalert 2.0, I'll look to find an alternative solution.

I added argument `closeOnClickOutside` to prevent closing when clicking outside, please install package from Github : 

```r

shinyApp(
  ui = fluidPage(
    tags$h1("Click the button"),
    actionButton(
      inputId = "success",
      label = "Launch a success sweet alert"
    )
  ),
  server = function(input, output, session) {
    observeEvent(input$success, {
      sendSweetAlert(
        session = session,
        title = "Success !!",
        text = "All in order",
        type = "success", 
        closeOnClickOutside = FALSE
      )
    })
  }
)

```

**Comment by mayeromain** [comment] 2018-01-29 13:57
Hello,

thank you very much for your update and thanks for the package it is very useful!

**Comment by pvictor** [comment] 2018-01-29 21:47
With a little JavaScript, argument `html` is back !
Glad you find the package useful :)

Try : 

```r
library("shiny")
library("shinyWidgets")

shinyApp(
  ui = fluidPage(
    tags$h1("Click the button"),
    actionButton(
      inputId = "sw_html",
      label = "Sweet alert with HTML"
    )
  ),
  server = function(input, output, session) {
    observeEvent(input$sw_html, {
      sendSweetAlert(
        session = session,
        title = "Success !!",
        text = tags$span(
          "In", tags$b("bold"), "and", tags$em("italic"),
          tags$br(),
          "and",
          tags$br(),
          "line",
          tags$br(),
          "breaks"
        ), 
        html = FALSE,
        type = "success"
      )
    })
  }
)
```

Victor

**Comment by mayeromain** [comment] 2018-01-30 07:02
Amazing! Very nice features thank you.

Romain

**Closed** 2018-01-30 08:51 UTC

**Comment by madmark81** [comment] 2018-01-30 09:12
just updated R and shinyWidgets, this example throws: 
Warning: Error in sendSweetAlert: unused argument (html = FALSE)
Stack trace (innermost first):
    68: observeEventHandler [#11]
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>

**Comment by mayeromain** [comment] 2018-01-30 09:14
have you installed the dev version of shinyWidgets?
```
library(devtools)
install_github("dreamRs/shinyWidgets")
```

**Comment by madmark81** [comment] 2018-01-30 09:32
yes just did, still same result

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyWidgets_0.4.1 shiny_1.0.5       

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  R6_2.2.2        htmltools_0.3.6 tools_3.4.3     Rcpp_0.12.15    jsonlite_1.5    digest_0.6.14   xtable_1.8-2    httpuv_1.3.5    mime_0.5

**Comment by mayeromain** [comment] 2018-01-30 10:01
the dev version is shinyWidgets_0.4.1.910. Try to remove it and re-install using the code I provided above.

**Comment by pvictor** [comment] 2018-02-12 12:04
Yes, it works in the latest version. I tried to go further by passing input/output, it seems to work but I don't know if it is very robust. Thanks for the improvement suggestion, it was cool to do.

If you want to try it : 

```r

library("shiny")
library("shinyWidgets")
library("ggplot2")

shinyApp(
  ui = fluidPage(
    tags$h1("Click the button"),
    actionButton(
      inputId = "sw_html",
      label = "Sweet alert with ggplot"
    ),
    tags$style(".swal-modal {width: 70%;}")
  ),
  server = function(input, output, session) {
    observeEvent(input$sw_html, {
      sendSweetAlert(
        session = session,
        title = "Yay an histogram!",
        text = tags$div(
          plotOutput(outputId = "plot"),
          sliderInput(
            inputId = "slider", label = "Number of bins",
            min = 20, max = 90, value = 60, width = "100%"
          )
        ),
        html = TRUE
      )
    })
    output$plot <- renderPlot({
      ggplot(diamonds, aes(carat)) +
        geom_histogram(bins = input$slider)
    })
  }
)
```

**Comment by mayeromain** [comment] 2018-02-12 12:36
you rock! This is really a good package thanks for all your updates.

**Comment by mayeromain** [comment] 2018-02-12 12:57
maybe it's a problem on my side but the `htlm = T` option on the `confirmSweetAlert` didn't seem to work:

> library("shiny")
> library("shinyWidgets")
> library("shinyjs")
> 
> ui <- fluidPage(
>   useShinyjs(),
>   tags$script("
>               Shiny.addCustomMessageHandler('resetValue', function(variableName) {
>               Shiny.onInputChange(variableName, null);
>               });
>               "),
>   tags$h1("Confirm sweet alert"),
>   actionButton(
>     inputId = "go",
>     label = "Launch confirmation dialog"
>   ),
>   actionButton(
>     inputId = "reset",
>     label = "reset value"
>   ),
>   verbatimTextOutput(outputId = "res")
> )
> 
> server <- function(input, output, session) {
>   
>   observeEvent(input$go, {
>     confirmSweetAlert(
>       session = session, inputId = "myconfirmation", type = "warning",
>       title = "Want to confirm ? </br>Or not?", danger_mode = TRUE,html = T
>     )
>   })
>   
>   observeEvent(input$reset,{
>     
>     session$sendCustomMessage(type = "resetValue", message = "myconfirmation")
>     
>   })
>   
>   observeEvent(input$myconfirmation,{
>     print(paste0("click value = ",input$myconfirmation))
>   })
>   
>   output$res <- renderPrint(input$myconfirmation)
>   
> }
> 
> shinyApp(ui = ui, server = server)
> 
> }

**Comment by pvictor** [comment] 2018-02-12 13:23
You have to use argument `text` to use HTML, and if yous use raw HTML, you'll have to escape it with `HTML` like this : 

```r
library("shiny")
library("shinyWidgets")


ui <- fluidPage(
  actionButton(
    inputId = "go",
    label = "Launch confirmation dialog"
  )
)

server <- function(input, output, session) {
  
  observeEvent(input$go, {
    sendSweetAlert(
      session = session, type = "warning", title = NULL,
      text = HTML("Is the HTML </br>Working or not?"), html =  TRUE
    )
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by DivadNojnarg** [comment] 2018-03-29 14:47
Hi Victor!
I noticed that it does not work on shiny-server pro:

```
Warning: Error in sendSweetAlert: unused argument (html = FALSE)
Stack trace (innermost first):
    65: observeEventHandler [/srv/shiny-server/case_studies_app_V3.2/server.R#485]
     1: runApp
```
no matter if it is set to TRUE or FALSE

Removing sendSweetAlert from the observeEvent would solve the problem. But this is not what I want to do :)

**Comment by pvictor** [comment] 2018-03-29 15:11
Hello David,
Yes I removed the arg on the last CRAN release, bad idea...
It's back in the dev version, try re-install the package from Github.
I'll try release to CRAN tomorrow.

Victor

**Comment by DivadNojnarg** [comment] 2018-03-29 15:20
I confirm the problem is fixed using:
```
devtools::install_github("dreamRs/shinyWidgets")
```

as well as paracetamol ^_^

Cheers
