### ISSUE TITLE
Weird behavior on updateAwesomeRadio()

### ISSUE THREAD

**Issue by iplc** [dreamRs/shinyWidgets#76] opened 2018-04-27 14:59 UTC
I have been working on app that uses several AwesomeRadio inputs that I want to update based on a reactive value.  When trying to update the **label** and **choices** values using `updateAwesomeRadio()` I noticed two weird behaviors:

First, updateAwesomeRadio() does not seem to update *both* the label and choices at the same time when those values depend on a variable.  
This is a minimal working example based on the example on the documentation:
```R
library("shiny")
library("shinyWidgets")

label_lst1 <- list(A = "Label A", B = "Label B")
choices_lst1 <- list(A = letters[1:5], B = 1:5)

ui <- fluidPage(
  shinyWidgets::awesomeRadio("radio1",
                             label = label_lst1$A, 
                             choices = choices_lst1$A),
  textInput(inputId = "updatelabel", label = "Update label")
)

server <- function(input, output, session) {
  observeEvent(input$updatelabel, {
    shinyWidgets::updateAwesomeRadio(session, inputId = "radio1", 
                                     label = label_lst1[[input$updatelabel]],
                                     choices = choices_lst1[[input$updatelabel]])
  })
}

shinyApp(ui = ui, server = server)
```

Changing the reactive value `input$updatelabel` to either 'A' or 'B' only updates the choices on the radio, instead of updating the choices **and** the label. If we switch the server to:  
```R
server <- function(input, output, session) {
  observeEvent(input$updatelabel, {
    shinyWidgets::updateAwesomeRadio(session, inputId = "radio1", 
                                     label = label_lst1[[input$updatelabel]])
    shinyWidgets::updateAwesomeRadio(session, inputId = "radio1", 
                                     choices = choices_lst1[[input$updatelabel]])
  })
}
```
it works as expected. Does updateAwesomeRadio() only update one value at a time? I could not find any reference to it on the documentation, although the examples given only show one of the two being updated.

The second weird thing is that when there are more than one awesomeRadio inputs than only the first one is updated. This could be a separate issue alone, but I think it makes sense to put both of them here.  
Here's an example:
```R
library("shiny")
library("shinyWidgets")

label_lst1 <- list(A = "Label A", B = "Label B")
label_lst2 <- list(A = "Label A", B = "Label B")

choices_lst1 <- list(A = letters[1:5], B = 1:5)
choices_lst2 <- list(A = letters[6:10], B = 6:10)

ui <- fluidPage(
  shinyWidgets::awesomeRadio("radio1",
                             label = label_lst1$A, 
                             choices = choices_lst1$A),
  
  shinyWidgets::awesomeRadio("radio2",
                             label = label_lst2$A, 
                             choices = choices_lst2$A),
  
  textInput(inputId = "updatelabel", label = "Update label")
)

server <- function(input, output, session) {
  
  observeEvent(input$updatelabel, {
    shinyWidgets::updateAwesomeRadio(session, inputId = "radio1", 
                                     label = label_lst1[[input$updatelabel]])
    shinyWidgets::updateAwesomeRadio(session, inputId = "radio1", 
                                     choices = choices_lst1[[input$updatelabel]])
    
    shinyWidgets::updateAwesomeRadio(session, inputId = "radio2", 
                                     label = label_lst2[[input$updatelabel]])
    shinyWidgets::updateAwesomeRadio(session, inputId = "radio2", 
                                     choices = choices_lst2[[input$updatelabel]])
  })
}

shinyApp(ui = ui, server = server)
```
On this example, changing `input$updatelabel` to A or B only has an effect on the first radio. Why is that?  

Is this the expected behavior of updateAwesomeRadio()?

**Comment by pvictor** [comment] 2018-05-01 09:16
Wow that was weird! I had trouble finding the cause of the bug ! 
This was because the choices in list B are numerics and not characters... Choices were correctly generated but default selected value if not provided is the first element of vector, and passing a numeric cause a JavaScript error, and after that occure, nothing works anymore...

First bug caused second one.

It's fixed in dev version, please re-install from Github.
Else you've to convert your choices to characters, e.g : 

```r
library("shiny")
library("shinyWidgets")

label_lst1 <- list(A = "Label A", B = "Label B")
choices_lst1 <- list(A = LETTERS[1:5], B = as.character(1:5))

ui <- fluidPage(
  shinyWidgets::awesomeRadio(
    inputId = "radio1",
    label = label_lst1$A,
    choices = choices_lst1$A
  ),
  radioButtons(
    inputId = "updatelabel", 
    label = "Update label", 
    choices = c("A", "B")
  )
)

server <- function(input, output, session) {
  observeEvent(input$updatelabel, {
    updateAwesomeRadio(
      session = session, inputId = "radio1", 
      label = label_lst1[[input$updatelabel]],
      choices = choices_lst1[[input$updatelabel]]
    )
  })
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by iplc** [comment] 2018-05-02 10:47
Hi Victor,

Thank you very much for taking the time to look through this issue. I can confirm that by re-installing from Github the issue is fixed!

**Closed** 2018-05-02 14:58 UTC
