### ISSUE TITLE
Error in dropdown with style

### ISSUE THREAD

**Issue by KieuTDo** [dreamRs/shinyWidgets#137] opened 2018-12-18 08:58 UTC
In version 0.4.4 if dropdown is used with style, the error occurs that first argument is invalid.

E.g.:

dropdown(numericInput("numid", "Numeric input", value=0), style="unite")

This worked fine with version 0.4.3.

Thank you!

**Comment by pvictor** [comment] 2018-12-20 14:01
Hello,

This works fine for me. Are you sure the error is caused by this ?

Victor

**Comment by samfielding** [comment] 2019-02-01 14:44
I can replicate this in 0.4.4 if I try to create the dropdown using renderUI and uiOutput with the example code taken from the man page [https://rdrr.io/cran/shinyWidgets/man/dropdown.html](https://rdrr.io/cran/shinyWidgets/man/dropdown.html).

Here is the working version from the man page:

```
if (interactive()) {
  
  library("shiny")
  library("shinyWidgets")
  
  ui <- fluidPage(
    tags$h2("pickerInput in dropdown"),
    br(),
    dropdown(
      
      tags$h3("List of Input"),
      
      pickerInput(inputId = 'xcol2',
                  label = 'X Variable',
                  choices = names(iris),
                  options = list(`style` = "btn-info")),
      
      pickerInput(inputId = 'ycol2',
                  label = 'Y Variable',
                  choices = names(iris),
                  selected = names(iris)[[2]],
                  options = list(`style` = "btn-warning")),
      
      sliderInput(inputId = 'clusters2',
                  label = 'Cluster count',
                  value = 3,
                  min = 1, max = 9),
      
      style = "unite",
      icon = icon("gear"),
      status = "danger", width = "300px",
      animate = animateOptions(
        enter = animations$fading_entrances$fadeInLeftBig,
        exit = animations$fading_exits$fadeOutRightBig
      )
    ),
    
    plotOutput(outputId = 'plot2')
  )
  
  server <- function(input, output, session) {
    
    selectedData2 <- reactive({
      iris[, c(input$xcol2, input$ycol2)]
    })
    
    clusters2 <- reactive({
      kmeans(selectedData2(), input$clusters2)
    })
    
    output$plot2 <- renderPlot({
      palette(c("#E41A1C", "#377EB8", "#4DAF4A",
                "#984EA3", "#FF7F00", "#FFFF33",
                "#A65628", "#F781BF", "#999999"))
      
      par(mar = c(5.1, 4.1, 0, 1))
      plot(selectedData2(),
           col = clusters2()$cluster,
           pch = 20, cex = 3)
      points(clusters2()$centers, pch = 4, cex = 4, lwd = 4)
    })
    
  }
  
  shinyApp(ui = ui, server = server)
  
}
```

This gives me no errors.
And here is the same code I have rewritten to use uiOutput in ui and renderUI in server:

```
if (interactive()) {
  
  library("shiny")
  library("shinyWidgets")
  
  ui <- fluidPage(
    tags$h2("pickerInput in dropdown"),
    br(),
    
    uiOutput(outputId = "my_dropdown"),
    
    plotOutput(outputId = 'plot2')
  )
  
  server <- function(input, output, session) {
    
    output$my_dropdown <-
      renderUI({
        dropdown(
          
          tags$h3("List of Input"),
          
          pickerInput(inputId = 'xcol2',
                      label = 'X Variable',
                      choices = names(iris),
                      options = list(`style` = "btn-info")),
          
          pickerInput(inputId = 'ycol2',
                      label = 'Y Variable',
                      choices = names(iris),
                      selected = names(iris)[[2]],
                      options = list(`style` = "btn-warning")),
          
          sliderInput(inputId = 'clusters2',
                      label = 'Cluster count',
                      value = 3,
                      min = 1, max = 9),
          
          style = "unite",
          icon = icon("gear"),
          status = "danger", width = "300px",
          animate = animateOptions(
            enter = animations$fading_entrances$fadeInLeftBig,
            exit = animations$fading_exits$fadeOutRightBig
          )
        )
    })
    
    selectedData2 <- reactive({
      iris[, c(input$xcol2, input$ycol2)]
    })
    
    clusters2 <- reactive({
      kmeans(selectedData2(), input$clusters2)
    })
    
    output$plot2 <- renderPlot({
      palette(c("#E41A1C", "#377EB8", "#4DAF4A",
                "#984EA3", "#FF7F00", "#FFFF33",
                "#A65628", "#F781BF", "#999999"))
      
      par(mar = c(5.1, 4.1, 0, 1))
      plot(selectedData2(),
           col = clusters2()$cluster,
           pch = 20, cex = 3)
      points(clusters2()$centers, pch = 4, cex = 4, lwd = 4)
    })
    
  }
  
  shinyApp(ui = ui, server = server)
  
}
```
This gives me 

> Error: invalid first argument

in the browser and,

> Warning: Error in exists: invalid first argument
>   [No stack trace available]

in the R console.

Unless I comment out
`style = "unite",`
in which case it works (albeit without the styled dropdown button).

My sessionInfo():

> R version 3.5.2 (2018-12-20)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] shinyWidgets_0.4.4 shiny_1.2.0       
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.0       packrat_0.5.0    digest_0.6.18    later_0.7.5      mime_0.6         R6_2.3.0         xtable_1.8-3    
>  [8] jsonlite_1.6     magrittr_1.5     scales_1.0.0     rlang_0.3.1      promises_1.0.1   tools_3.5.2      munsell_0.5.0   
> [15] httpuv_1.4.5     compiler_3.5.2   colorspace_1.4-0 htmltools_0.3.6 

If I try the same with shinyWidgets_0.4.3 I don't get any errors and there is no visible difference between using dropdown in ui and using it in a in renderUI with uiOutput.

**Comment by DavidBarke** [comment] 2019-02-15 21:54
I encountered the same error as @KieuTDo  and I think I found its reason in [sw-dropdown.R](https://github.com/dreamRs/shinyWidgets/blob/master/R/sw-dropdown.R):

If another style than "default" is used, the dropdown button is generated with actionBttn. If used in renderUI this actionBttn must have a non-null inputId. Therefore you could call dropdown with an inputId inside of renderUI to get the other styles.

**Comment by pvictor** [comment] 2019-02-18 08:31
Thanks @samfielding for the example and thanks @DavidBarke for the traceback. I think this was caused by the default id assigned to the button, it's now fixed.
Tell me if this is good for you !

Victor

**Comment by DavidBarke** [comment] 2019-02-19 09:23
Thanks for the quick response, it works!

David

**Closed** 2019-11-08 08:13 UTC
